worker_processes 1;

events {
    worker_connections 4096;
}

http {
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        listen 443 quic reuseport;
        listen [::]:443 quic reuseport;

        http3 on;
        http2 on;
        gzip  on;

        server_name sepehr-ai.com;

        ssl_session_timeout 1h;
        ssl_session_tickets off;
        ssl_prefer_server_ciphers on;
        ssl_session_cache   shared:SSL:10m;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_certificate_key /etc/ssl/private/sepehr-ai.com.key;
        ssl_certificate     /etc/ssl/certs/sepehr-ai.com.fullchain.pem;
        ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305";

        add_header Alt-Svc 'h3-23=":443"; ma=86400' always;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

        location / {
            proxy_pass          http://127.0.0.1:3000;

            proxy_http_version  1.1;
            proxy_set_header    Host $host;
            proxy_set_header    X-Real-IP $remote_addr;
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto $scheme;
        }

        # Optional: Serve static assets directly
        # location /_next/static/ {
        #     expires 1y;
        #     access_log off;
        #     alias  /home/sepehr/sepehr-ai/.next/static/;
        # }
    }
}